### ISSUE TITLE
Waydroid-magisk has missing dbus-python dependency.

### ISSUE THREAD

**Issue by JMarcosHP** [Jonatas-Goncalves/MaxxedSUSE#5] opened 2024-04-25 19:03 UTC

**Comment by Jonatas-Goncalves** [comment] 2024-04-26 09:57
I updated the package with the correct dependency. please test and let me know.

After installing the package, these commands must be executed:
sudo waydroid_magisk install
sudo waydroid_magisk setup

**Comment by JMarcosHP** [comment] 2024-04-26 18:32
> I updated the package with the correct dependency. please test and let me know.
> 
> After installing the package, these commands must be executed: sudo waydroid_magisk install sudo waydroid_magisk setup

Can waydroid-magisk and waydroid (normal pkg) be installed on the same system or causes conflict?

**Comment by JMarcosHP** [comment] 2024-04-26 18:43
It isn't working, the `su` binary doesn't exist.

![Captura de pantalla_20240426_124022](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/9382dd26-7d41-4017-a6ea-e232fd594e86)

**Comment by JMarcosHP** [comment] 2024-04-26 18:56
I think we need a particular kernel to get it working, as the waydroid_script maintainer said in [this reddit post.](https://www.reddit.com/r/linuxmasterrace/comments/13tjb3m/magisk_on_waydroid/)

**Comment by JMarcosHP** [comment] 2024-04-26 19:16
[There is another installation script.](https://github.com/mistrmochov/magiskWaydroid)

**Comment by JMarcosHP** [comment] 2024-04-26 19:18
You can make a pull request to integrate this script to the current opensuse repo.

**Comment by JMarcosHP** [comment] 2024-04-26 19:34
It works. yey!
Just start a waydroid session and execute the script, select option 1, then wait for magisk delta installation, start waydroid again and check if magisk is installed, finally reboot waydroid.

![Captura de pantalla_20240426_132735](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/9c4d4493-a8c6-43e2-92e3-863afd1aea95)
![Captura de pantalla_20240426_132759](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/408ec6d7-c34c-4d97-ab44-e80a0303d65f)
![Captura de pantalla_20240426_133105](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/74f658bc-e241-483a-94ed-2b2fce101cc3)
![Captura de pantalla_20240426_133117](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/6b9b238c-555a-4112-8a53-2f1ffa36a784)

**Comment by JMarcosHP** [comment] 2024-04-26 19:38
And if you want to update magisk, install directly modifing /system partition because the first option isn't working.

![Captura de pantalla_20240426_133550](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/5f2426ce-0d04-4e75-b301-aebe58d1383b)

![Captura de pantalla_20240426_133536](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/b24378c3-1e7e-46df-b4bc-fa8163f50219)

**Comment by Jonatas-Goncalves** [comment] 2024-04-26 19:46
I don't understand, is my waydroid-magisk package working or this script:
https://github.com/mistrmochov/magiskWaydroid

**Comment by JMarcosHP** [comment] 2024-04-26 19:47
> I don't understand, is my waydroid-magisk package working or this script: https://github.com/mistrmochov/magiskWaydroid

The script, the package is not working

**Comment by JMarcosHP** [comment] 2024-04-26 19:49
The script is another alternative to the current package.

**Comment by Jonatas-Goncalves** [comment] 2024-04-26 20:22
I will calmly analyze the package's python script along with this other one and try to understand what is happening.

Anything I recreate the package using this script since it is functional.

**Comment by Jonatas-Goncalves** [comment] 2024-04-28 20:01
I was analyzing what happens: my package uses the nitanmarcel repository, and it uses the HuskyDG repository which uses Kitsuni Magisk, recently HuskyDG has changed the mounting su location from /system/bin to /apex/com .android.runtime/bin. This is to reduce bind mount.

I could simply change the waydroid-magisk path to use this path, but from what I studied in the issues, HuskyDG removed the binary and will return to the original path in the next release.

In the meantime, I'm going to try to use the official Magisk Binary in the same existing python script as Nitanmarcel, just changing the download and installation, so as not to be too much work.

Regarding the repository you indicated, I am very suspicious about the origin of the su and magisk binary, the repository does not have the source code, only the magisk binary of which I did not find the origin, I recommend that you do not use this script.

**Comment by JMarcosHP** [comment] 2024-04-29 18:45
> I was analyzing what happens: my package uses the nitanmarcel repository, and it uses the HuskyDG repository which uses Kitsuni Magisk, recently HuskyDG has changed the mounting su location from /system/bin to /apex/com .android.runtime/bin. This is to reduce bind mount.
> 
> I could simply change the waydroid-magisk path to use this path, but from what I studied in the issues, HuskyDG removed the binary and will return to the original path in the next release.
> 
> In the meantime, I'm going to try to use the official Magisk Binary in the same existing python script as Nitanmarcel, just changing the download and installation, so as not to be too much work.
> 
> Regarding the repository you indicated, I am very suspicious about the origin of the su and magisk binary, the repository does not have the source code, only the magisk binary of which I did not find the origin, I recommend that you do not use this script.

Ok, thanks for telling me. I will remove the magisk binary and the script.
Waiting for changes on the current package to start testing again.

**Comment by JMarcosHP** [comment] 2024-05-03 19:34
Missing `pkgconfig(python311-ConfigUpdater)` dependency.

**Comment by Jonatas-Goncalves** [comment] 2024-05-11 07:15
I changed the waydroid-magisk package to the [mistrmochov](https://github.com/mistrmochov/magiskWaydroid) script.
After a lot of research and testing I haven't found another working solution at the moment.

However, I took the time to check the mistrmochov package in depth and I understood why it is not on github when I tried to reproduce a similar solution, which is the maximum file size on github.

The mistrmochov package is the exact magisk delta from [HuskyDG](https://github.com/HuskyDG/magisk-files), I extracted the apk and checked it file by file, and at first it seemed to be the same as HuskyDG.

That's why I inserted this script into the package and sent it to the repository, fixed the dependencies and it is working without problems.

Please test it and tell me if it worked.

**Comment by JMarcosHP** [comment] 2024-05-13 22:29
It's working with this mistrmochov script and your package.
Thanks a lot for your work.
Now you can propose your repository to waydroid's devs and write an installation guide for SUSE and propose the mistrmochov's script as recomended.
[https://docs.waydro.id/faq/community-projects-we-like](https://docs.waydro.id/faq/community-projects-we-like)

![Captura de pantalla_20240513_160905](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/effd0f0d-a7fd-492d-814a-97f211a25e3d)
![Captura de pantalla_20240513_162701](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/8d14fc22-5d67-4e13-9a04-deb6da31624a)


You can install magisk and LSposed to the system partition to make sure the system OTA updates don't remove root access.

**Comment by Jonatas-Goncalves** [comment] 2024-05-14 01:55
Waydroid will only include official or transparent code forms in their guide, my repository is not official.

I'm trying to open a request for a devel project on opensuse, but I'm running out of time right now.
By having a devel project I can release my packages in the factory to be available to everyone even outside of MaxxedSuse.
Some of the problems of not having a Devel: The [libnvidia-container](https://build.opensuse.org/request/show/1171206) package that is in my repository is the only one updated and currently working, I sent it to SUSE:SLE a few days ago and nothing, other Devel project maintainers create difficulties as it is here about [oversteer](https://build.opensuse.org/request/show/1170631).
To escape these bureaucracies, I intend to request development project, but I need time, as soon as I finish the adjustments for the next update that I want to make here I will request it.

**Comment by Jonatas-Goncalves** [comment] 2024-05-14 02:12
Closing issue once it has been completed.

**Closed as completed by Jonatas-Goncalves** 2024-05-14 02:12 UTC
