### ISSUE TITLE
Waydroid storage issue.

### ISSUE THREAD

**Issue by JMarcosHP** [Jonatas-Goncalves/MaxxedSUSE#13] opened 2024-05-21 02:40 UTC
I can't save or download data from browsers on waydroid.

![image](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/1ebc6447-2fb4-463b-b56f-f25ac18cc2ae)

**Comment by JMarcosHP** [comment] 2024-05-21 02:43
![image](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/24d73c06-ecb9-4ca8-8edc-a32c07eb1e52)
![image](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/918a1a8a-59f7-4e07-8f62-32481e6a1fae)

**Comment by JMarcosHP** [comment] 2024-05-21 02:48
And I can't open files from shared storage.
![image](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/60041438-9b60-4b48-926d-df259f6f9fe8)

**Comment by JMarcosHP** [comment] 2024-05-21 02:49
I think there are some policy permission issues.

**Comment by JMarcosHP** [comment] 2024-05-21 03:12
I reinstalled waydroid, and it works again.
I think the magisk script + system upgrades corrupted in some way my installation.
Can you test it?

**Comment by Jonatas-Goncalves** [comment] 2024-05-24 18:42
I had the same problem here, but unfortunately I can't support it since the binary is pre-compiled and I don't have access to make changes.
In the package, the execution permissions of the directories and binaries are correct, I do not have access or knowledge to modify the binary that is installed within magisk.

There's not much we can do until we find another alternative.

**Comment by Jonatas-Goncalves** [comment] 2024-05-28 19:14
Closing the issue since the problem is in the application's binary and there are no ways to change it, I will wait for news from the mistrmochov [main](https://github.com/mistrmochov/magiskWaydroid) project to be included in the repository.

**Comment by Jonatas-Goncalves** [comment] 2024-05-28 19:17
Closing the issue since the problem is in the application's binary from  and there are no ways to change it, I will wait for news from the [mistrmochov](https://github.com/mistrmochov/magiskWaydroid) main project or [HuskyDG](https://github.com/HuskyDG/magisk-files) to be included in the repository.

**Comment by Jonatas-Goncalves** [comment] 2024-05-28 19:18
Closing the issue since the problem is in the application's binary and there are no ways to change it, I will wait for news from [mistrmochov](https://github.com/mistrmochov/magiskWaydroid) the main project or [HuskyDG](https://github.com/HuskyDG/magisk-files) to be included in the repository.

**Closed as completed by Jonatas-Goncalves** 2024-05-28 19:18 UTC
